[package]
name = "tcp"
version = "0.1.0"
edition = "2024"
authors = ["Huseen Munye"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/hmunye/tcp"
description = """
User-space implementation of the Transmission Control Protocol (TCP), based
primarily on RFC 793.
"""
categories = ["network-programming"]
keywords = ["io", "network"]

[features]
# Enable nothing.
default = []

# Enable everything.
full = ["trace"]

trace = []

[dependencies]

[dev-dependencies]
proptest = "1.7.0"
