[package]
name = "tcp-tun"
version = "0.1.0"
edition = "2024"
authors = ["Huseen Munye"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/hmunye/tcp"
description = """
Linux-only echo server built with a user-space TCP stack over a TUN interface.
"""
categories = ["network-programming"]
keywords = ["io", "network", "non-blocking"]

[dependencies]
tcp = { path = "../tcp", features = ["full"] }
rio = { git = "https://github.com/hmunye/rio.git", version = "0.1.0", features = ["macros", "time", "io"] }
