# https://github.com/jonhoo/rust-ci-conf/blob/main/.github/workflows/check.yml
#
# This workflow runs whenever a PR is opened or updated, or a commit is pushed
# to main. It runs several checks:
#
# - fmt:    checks that the code is formatted according to rustfmt
# - clippy: checks that the code has no clippy warnings
# - doc:    checks that the documentation builds without any errors
# - hack:   checks combinations of feature flags
# - msrv:   checks that the MSRV specified in the crate is correct
permissions:
  contents: read

# This configuration enables maintainers of this repository to create a branch
# and PR based on the new branch. Restricting the push trigger to the main
# branch ensures the PR only gets built once.
on:
  push:
    branches: [main]
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for 
# that PR. Ensures that we don't waste CI time, and return results quicker.
#
# https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: CI
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # branch=master
        with:
          toolchain: stable
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        # Get early warning of new lints which are regularly introduced in beta 
        # channels.
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # branch=master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all-targets
  doc:
    # Run docs generation on nightly rather than stable. This enables features 
    # like:
    #
    # https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html
    #
    # This allows an API be documented as only available on specific platforms.
    runs-on: ubuntu-latest
    name: nightly / doc
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # branch=master
        with:
          toolchain: nightly
      - name: Install cargo-docs-rs
        uses: dtolnay/install@982daea0f5d846abc3c83e01a6a1d73c040047c1 # branch=cargo-docs-rs
      - name: cargo docs-rs (tcp)
        run: cargo docs-rs -p tcp
      - name: cargo docs-rs (tcp-tun)
        run: cargo docs-rs -p tcp-tun
  hack:
    # cargo-hack checks combinations of feature flags to ensure that features
    # are all additive, which is required for feature unification.
    runs-on: ubuntu-latest
    name: ubuntu / stable / features
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # branch=master
        with:
          toolchain: stable
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@1ed3272338f573e042a2e6bca3893aa19f43b47a # tag=v2.71.3
        with:
          tool: cargo-hack
      # No target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      #
      # --feature-powerset runs for every combination of features.
      - name: cargo hack
        run: cargo hack --feature-powerset check
  msrv:
    # Check that we can build using the MSRV specified by this crate.
    runs-on: ubuntu-latest
    # We use a matrix here because env can't be used in job names.
    #
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      matrix:
        msrv: ["1.85.0"] # 2024 edition
    name: ubuntu / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # branch=master
        with:
          toolchain: ${{ matrix.msrv }}
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # tag=v5.0.4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo
      - name: cargo +${{ matrix.msrv }} check
        # TODO: Remove `-p tcp` when refactoring `tcp-tun`
        run: cargo check -p tcp
